module.exports = {
	plugins: ["@trivago/prettier-plugin-sort-imports", "prettier-plugin-tailwindcss"],
	importOrder: [
		"^react(.*)$",
		"^next(.*)$",
		"<THIRD_PARTY_MODULES>",
		"^@/(.*)$",
		"^[./]",
	],
	importOrderSeparation: true,
	importOrderSortSpecifiers: true,
	printWidth: 88,
	tabWidth: 2,
	useTabs: true,
	semi: true,
	singleQuote: false,
	quoteProps: "as-needed",
	trailingComma: "es5",
	bracketSpacing: true,
	bracketSameLine: false,
	arrowParens: "avoid",
	endOfLine: "lf",
};
